import { ArrowRight, BookOpen, Church, Flame, HandHeart, HeartHandshake, Users } from 'lucide-react';
import SubpageNav from '@/components/SubpageNav';

const values = [
  { icon: BookOpen, title: 'Bible-Based', text: 'Scripture shapes what we believe, how we live, and how we serve.' },
  { icon: HeartHandshake, title: 'Gospel Partnership', text: 'We work with like-minded believers to strengthen the Church and advance the gospel.' },
  { icon: HandHeart, title: 'Gospel-Fueled Generosity', text: 'We give joyfully and sacrificially, especially in care for vulnerable children.' },
  { icon: Flame, title: 'Faith-Driven Simplicity', text: 'We plan wisely, depend on the Holy Spirit, and choose faithfulness over applause.' },
];

export default function AboutPage() {
  return <main className="about-page">
    <SubpageNav/>
    <section className="about-hero"><div className="about-hero-photo" style={{ backgroundImage: "url('../cape-town-hero.png')" }}/><div className="about-hero-shade"/><div className="about-hero-copy"><p>Our story · Our conviction</p><h1>A fire for the gospel.<br/><em>A home for mission.</em></h1><span>Iziko Missions exists to see Christ-centred churches and leaders flourish across South Africa.</span></div></section>
    <section className="about-origin"><div className="about-label">01 — Why Iziko</div><div className="origin-grid"><h2>A gathering place of <em>warmth, truth, and spiritual life.</em></h2><div><p className="origin-lead">“Iziko” is an isiXhosa word for a firepit—the centre of the home, where fire burns and community gathers.</p><p>We believe the local church should be just that: a place centred on the gospel of Jesus Christ, where people find belonging, grow in truth, and carry his light into their communities.</p></div></div><div className="origin-symbol"><Flame/><span>IZIKO</span><small>The hearth · The centre · The gathering place</small></div></section>
    <section className="about-story"><div className="story-photo"><img src="../work-leadership.png" alt="Local ministry leaders studying together"/></div><div className="story-copy"><div className="about-label light">02 — Our story</div><h2>Born from a burden for the <em>local church.</em></h2><p>Iziko Missions South Africa was born from a deep desire to see Christ-centred churches planted in the townships and cities of South Africa—led by local leaders and grounded in sound doctrine.</p><p>After more than fifteen years in ministry and community development, Sive Nogada became convinced that lasting transformation must keep Jesus and his Word at the centre.</p><div className="story-principles"><span><Church/> Churches planted</span><span><Users/> Leaders raised</span><span><HandHeart/> Children supported</span></div></div></section>
    <section className="founder-section"><div className="founder-intro"><div className="about-label">03 — Founder & President</div><h2>Meet<br/><em>Sive Nogada.</em></h2></div><div className="founder-body"><p className="founder-lead">Born and raised in Khayelitsha, Sive came to know Christ as a teenager through the faithful witness of a local missionary.</p><p>His journey has included pastoral ministry, theological formation, nonprofit leadership, and years of investing in people.</p><p>After living in California for over seven years, Sive and his family are returning home to Cape Town to plant Magnify Church and lead Iziko Missions full-time.</p><a className="founder-video" href="https://www.youtube.com/watch?v=A5KUkcj6_tE" target="_blank" rel="noopener noreferrer">Watch Sive’s story <ArrowRight size={17}/></a></div></section>
    <section className="values-section"><div className="about-label light">04 — Our values</div><div className="values-heading"><h2>Convictions that<br/><em>shape our work.</em></h2><p>These commitments keep our ministry rooted, relational, generous, and faithful.</p></div><div className="values-list">{values.map(({icon:Icon,title,text},i)=><article key={title}><span>0{i+1}</span><Icon/><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <section className="about-cta"><p>Your place in the story</p><h2>Pray with us.<br/><em>Partner with us.</em></h2><div><a href="../get-involved/">Get involved <ArrowRight size={17}/></a><a href="../team/">Meet the Team</a><a href="https://www.zeffy.com/en-US/donation-form/support-the-nogadas" target="_blank" rel="noopener noreferrer">Give to the mission</a></div></section>
    <footer className="about-footer"><span>© 2026 Iziko Missions</span><a href="mailto:info@izikomission.org">info@izikomission.org</a><span>Registered 501(c)(3) · Federal Tax ID: 39-3246865</span></footer>
  </main>
}
