import { ArrowRight, BookOpen, Church, Flame, HandHeart, HeartHandshake, Users } from 'lucide-react';
import SubpageNav from '@/components/SubpageNav';

const values = [
  { icon: BookOpen, title: 'Bible-Based', text: 'We trust the sufficiency of Scripture to shape what we believe, how we live, and the priorities of our work.' },
  { icon: HeartHandshake, title: 'Gospel Partnership', text: 'We pursue like-minded ministry partnerships that advance the gospel and strengthen God’s kingdom.' },
  { icon: HandHeart, title: 'Gospel-Fueled Generosity', text: 'We give joyfully and sacrificially, extending Christ’s love through tangible care for vulnerable children.' },
  { icon: Flame, title: 'Faith-Driven Simplicity', text: 'We plan wisely, depend on the Holy Spirit, and choose faithfulness over outcome-driven ministry.' },
];

const philosophy = [
  { icon: Users, number: '01', title: 'Local Leadership', text: 'We prioritize equipping local leaders because sustainable mission is strongest when it is led from within the community.' },
  { icon: HeartHandshake, number: '02', title: 'Local Ownership', text: 'We foster long-term gospel advancement by helping local leaders and ministries grow toward financial sustainability.' },
  { icon: Church, number: '03', title: 'Local Church Focused', text: 'We believe discipleship is meant to take place in and through the local church, where faith is lived in community and accountability.' },
];

export default function AboutPage() {
  return <main className="about-page">
    <SubpageNav/>
    <section className="about-hero"><div className="about-hero-photo" style={{ backgroundImage: "url('../cape-town-hero.png')" }}/><div className="about-hero-shade"/><div className="about-hero-copy"><p>Our story · Our conviction</p><h1>A fire for the gospel.<br/><em>A home for mission.</em></h1><span>To plant Christ-centered churches, raise leaders with conviction, and support vulnerable children.</span></div></section>
    <section className="about-origin"><div className="about-label">01 — Why Iziko</div><div className="origin-grid"><h2>Christ at the centre of <em>life, church, and mission.</em></h2><div><p className="origin-lead">“Iziko” is an isiXhosa word for a firepit—the centre of the home, where warmth, wisdom, and community naturally gather.</p><p>In the same way, we exist to make Christ known as the true centre of life. We plant Christ-centered churches, raise leaders with conviction, and care for vulnerable children so that his light and life may reach every heart.</p><p>Christ and his Word remain at the centre of all we do. In him we discover our purpose: to know him, make him known, and proclaim his redeeming love.</p></div></div><div className="origin-symbol"><img className="origin-emblem" src="../iziko-emblem-3d.png" alt="Iziko Missions fire and community emblem"/><span>IZIKO</span><small>The hearth · The centre · The gathering place</small></div></section>
    <section className="about-story"><div className="story-photo"><img src="../work-leadership.png" alt="Local ministry leaders studying together"/></div><div className="story-copy"><div className="about-label light">02 — Our story</div><h2>Born from a burden for the <em>local church.</em></h2><p>Iziko Missions South Africa was born from a deep desire to see Christ-centred churches planted in the townships and cities of South Africa—led by local leaders and grounded in sound doctrine.</p><p>After more than fifteen years in ministry and community development, Sive Nogada became convinced that lasting transformation must keep Jesus and his Word at the centre.</p><div className="story-principles"><span><Church/> Churches planted</span><span><Users/> Leaders raised</span><span><HandHeart/> Children supported</span></div></div></section>
    <section className="founder-section"><div className="founder-intro"><div className="about-label">03 — Founder & President</div><h2>Meet<br/><em>Sive Nogada.</em></h2></div><div className="founder-body"><p className="founder-lead">Born and raised in Khayelitsha, Sive came to know Christ as a teenager through the faithful witness of a local missionary.</p><p>His journey has included pastoral ministry, theological formation, nonprofit leadership, and years of investing in people.</p><p>After living in California for over seven years, Sive and his family are returning home to Cape Town to plant Magnify Church and lead Iziko Missions full-time.</p><a className="founder-video" href="https://www.youtube.com/watch?v=A5KUkcj6_tE" target="_blank" rel="noopener noreferrer">Watch Sive’s story <ArrowRight size={17}/></a></div></section>
    <section className="values-section"><div className="about-label light">04 — Our values</div><div className="values-heading"><h2>Convictions that<br/><em>shape our work.</em></h2><p>These commitments keep our ministry rooted, relational, generous, and faithful.</p></div><div className="values-list">{values.map(({icon:Icon,title,text},i)=><article key={title}><span>0{i+1}</span><Icon/><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <section className="philosophy-section"><div className="about-label">05 — Our ministry philosophy</div><div className="philosophy-heading"><h2>Local leaders.<br/><em>Local ownership.</em><br/>Local churches.</h2><p>Our approach is designed for faithful, sustainable gospel ministry that is rooted in the communities it serves.</p></div><div className="philosophy-grid">{philosophy.map(({icon:Icon,...item})=><article key={item.number}><div><span>{item.number}</span><Icon/></div><h3>{item.title}</h3><p>{item.text}</p></article>)}</div></section>
    <section className="about-cta"><p>Your place in the story</p><h2>Pray with us.<br/><em>Partner with us.</em></h2><div><a href="../get-involved/">Get involved <ArrowRight size={17}/></a><a href="../team/">Meet the Team</a><a href="https://www.zeffy.com/en-US/donation-form/support-the-nogadas" target="_blank" rel="noopener noreferrer">Give to the mission</a></div></section>
    <footer className="about-footer"><span>© 2026 Iziko Missions</span><a href="mailto:info@izikomission.org">info@izikomission.org</a><span>Registered 501(c)(3) · Federal Tax ID: 39-3246865</span></footer>
  </main>
}
